ALTER TABLE `nova`.`BATCH_JOB_EXECUTION`
CHANGE COLUMN `EXIT_CODE` `EXIT_CODE` VARCHAR(10) NULL DEFAULT NULL;

ALTER TABLE `nova`.`BATCH_STEP_EXECUTION`
CHANGE COLUMN `EXIT_CODE` `EXIT_CODE` VARCHAR(10) NULL DEFAULT NULL;
