USE nova;

DROP PROCEDURE IF EXISTS `abandon_nflow_jobs`;

DELIMITER $$
CREATE PROCEDURE `abandon_nflow_jobs`(in nflow varchar(255))
BEGIN

UPDATE BATCH_JOB_EXECUTION
  INNER JOIN BATCH_JOB_INSTANCE ON BATCH_JOB_INSTANCE.JOB_INSTANCE_ID = BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
SET BATCH_JOB_EXECUTION.STATUS = 'ABANDONED',
  BATCH_JOB_EXECUTION.EXIT_MESSAGE = CONCAT('Job manually abandoned @ ', DATE_FORMAT(now(), '%Y-%m-%d %T:%f'))
WHERE BATCH_JOB_INSTANCE.JOB_NAME in ( SELECT checkNflow.NAME
				FROM NFLOW_CHECK_DATA_NFLOWS c
				inner join NFLOW f on f.name = nflow and c.NFLOW_ID = f.id
				inner join NFLOW checkNflow on checkNflow.id = c.CHECK_DATA_NFLOW_ID
				UNION
				SELECT nflow from dual )
  AND BATCH_JOB_EXECUTION.STATUS = 'FAILED';

END$$
DELIMITER ;
